### ISSUE TITLE
Routing to different DICOM stores, based on AETitle... but dynamically

### ISSUE THREAD

**Issue by dbousamra** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#100]
We currently use Orthanc as our DIMSE -> dicomweb proxy. We have a simple Lua script that extracts the name of dicomweb store from the AEtitle, and then issues an HTTP post. It works well enough, but we are looking to migrate off it for other reasons.

Evaluating this service, I noticed there is the ability to route to different dicomweb stores. But they must be declared statically, ahead of time.

What is the recommended way to achieve dynamic routing, where you use the AETitle (or perhaps some field inside the DICOM instance itself) to deduce the destination dicomweb store.

I can think of a few different ways to achieve this, and I am happy to do the development myself, but I would like to know your thoughts on the best way.

**Comment by danielbeaudreau** [comment]
How many destinations do you need to support? 
Is it possible for you to generate a static config with an entry for each AE Title?

**Comment by dbousamra** [comment]
Hey danie.

Right now I only need to target < 10. But if my business grows.... i might be targeting 100 +. A static option is probably feasible for now thinking about it.

**Comment by danielbeaudreau** [comment]
Hi Narendra, at the moment the adapter does not support DicomWeb to DIMSE conversion. Feel free to file a separate feature request bug to track this, and if you're interested in contributing support for this feature to the repo, please let me know.
