### ISSUE TITLE
Error when Import Adapter Docker image locally

### ISSUE THREAD

**Issue by rajarordev** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#104]
I got the below error when try to Running Docker image locally by using the below command

docker run \
-p 2579:2579 \
-v /path/to/google_credentials.json:/credentials -e GOOGLE_APPLICATION_CREDENTIALS='/credentials' \
-v /path/to/AETs.json:/AETs \
${TAG} \
gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-import:0.1.1 \
--aet_dictionary=/AETs \
--dimse_aet=IMPORTADAPTER \
--dimse_port=2579 \
--dicomweb_address=https://healthcare.googleapis.com/v1beta1/projects/${PROJECT}/locations/${LOCATION}/datasets/${DATASET}/dicomStores/${DICOMSTORE}/dicomWeb \
--oauth_scopes=https://www.googleapis.com/auth/cloud-platform \
--monitoring_project_id=${PROJECT} \
--verbose

Error:

Exception in thread "main" com.beust.jcommander.ParameterException: Was passed main parameter 'gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-import:0.2.15' but no main parameter was defined in your arg class
        at com.beust.jcommander.JCommander.initMainParameterValue(JCommander.java:936)
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:752)
        at com.beust.jcommander.JCommander.parse(JCommander.java:340)
        at com.beust.jcommander.JCommander.parse(JCommander.java:319)
        at com.google.cloud.healthcare.imaging.dicomadapter.ImportAdapter.main(ImportAdapter.java:52)
Can you please help to fix this issue?

**Comment by dzelemba** [comment]
Can you share the actual command that led to this error? The example command is using version 0.1.1 whereas the error message shows 0.2.15. It may just be an error with newlines. I've double checked that the instructions at https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/wiki/Running-Docker-image-locally still work for me.

**Comment by rajarordev** [comment]
Please find the below command i used for this
docker run -v /home/raja/testqr/migration-40f7dc206461.json:/credentials -e GOOGLE_APPLICATION_CREDENTIALS='/credentials' -v /home/raja/testqr/AETs.json:/AETs gcr.io/migration/dicom-import-adapter gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-import:0.2.15 --aet_dictionary=/AETs --dimse_aet=IMPORTADAPTER --dimse_port=2579 --dicomweb_address=https://healthcare.googleapis.com/v1/projects/migration/locations/us-central1/datasets/test-dataset/dicomStores/test-datastore/dicomWeb --oauth_scopes=https://www.googleapis.com/auth/cloud-platform --monitoring_project_id=migration --verbose

Please let me know if i need to corret any.

Thank you very much for your time.

**Comment by dzelemba** [comment]
What is the "gcr.io/migration/dicom-import-adapter" portion of the command intended for? Once I removed it from your command it worked for me (I also removed the AET part since I didn't have a file handy, but I don't think that should affect it):

```
docker run -v <my_path>:/credentials -e GOOGLE_APPLICATION_CREDENTIALS='/credentials' gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-import:0.2.15 --dimse_aet=IMPORTADAPTER --dimse_port=2579 --dicomweb_address=https://healthcare.googleapis.com/v1/projects/migration/locations/us-central1/datasets/test-dataset/dicomStores/test-datastore/dicomWeb --oauth_scopes=https://www.googleapis.com/auth/cloud-platform --monitoring_project_id=migration --verbose
```

**Comment by rajarordev** [comment]
This poriton "gcr.io/migration/dicom-import-adapter" is ${TAG} value. But when i execute the above command now i got the error Exception in thread "main" java.io.IOException: Error reading credential file from environment variable GOOGLE_APPLICATION_CREDENTIALS, value '/credentials': File does not exist. I think this is the problem from mount local credentials file as a volume in docker command. Can you correct me if i am wrong?

**Comment by dzelemba** [comment]
Yes that error message indicates some issue with mounting the local file in the container.

**Comment by dzelemba** [comment]
I'm going to close this issue now due to inactivity, but if you're still having problems let me know!
