### ISSUE TITLE
Issue while executing dcmsend

### ISSUE THREAD

**Issue by AppstuteAratiGadgil** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#105]
I have created dicomstore. Also deployed dicom adapter using Google Kubernetes Engine. 
URL: https://cloud.google.com/healthcare/docs/how-tos/dicom-connect-pacs
When i use dcmsend command, getting following error.
ERROR com.google.cloud.healthcare.DicomWebClientJetty - STOW-RS response:
{"error": {"code": 403,"message": "Request had insufficient authentication scopes.","status": "PERMISSION_DENIED"}}. 

Please let me know ,if we are missing something.

**Comment by dzelemba** [comment]
Looks like the instructions have a missing component, I'll fix that. When creating the GKE cluster you have to specify the correct scopes via ``--scopes https://www.googleapis.com/auth/cloud-healthcare``. E.g.

```
gcloud container clusters create dicom-adapter --zone=us-central1-a --scopes https://www.googleapis.com/auth/cloud-healthcare
```

If you also want to run the Export adapter, you'll need to include the PubSub scope as well `https://www.googleapis.com/auth/pubsub`.
