### ISSUE TITLE
I import image in gcp dicom store, but on my pubsub topic assigned dicom store is not publishing message

### ISSUE THREAD

**Issue by ankitdata** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#107]
**steps**

I create

dicom dataset
inside dataset dicom store
topic for dicom store

**Issue**

I am trying to import dcm image to dicom store from storage bucket operation is showing Success in dicom-store operations but message is not publishing on assigned topic.

_Healthcare and Pubsub API are Enable and granted permissions._

**Comment by dzelemba** [comment]
Hello thanks for reaching out! This GitHub repo is just for the DICOM Adapter, for help with general issues using the Healthcare API please see https://cloud.google.com/healthcare/docs/getting-support for options. I see you've also posted on StackOverflow, so I'll provide an answer there.

**Comment by ankitdata** [comment]
**solution**.
https://stackoverflow.com/questions/63741105/i-import-image-in-gcp-dicom-store-but-on-my-pubsub-topic-assigned-dicom-store-i
