### ISSUE TITLE
Add Instructions for Running Adaptor Locally Without Having to Compile

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#12]
Using something like:

docker run gcr.io/cloud-healthcare-containers/dicom-import-adapter:latest --dimse_aet=IMPORTADAPTER --dimse_port=2575 --dicomweb_addr=https://healthcare.googleapis.com/v1beta1 --dicomweb_stow_path=/projects/<pid>/locations/us-central1/datasets/test/dicomStores/test/dicomWeb/studies

But application default credentials need to be passed to the container somehow.

**Comment by red1408** [comment]
Yeah.. normal local runs use GOOGLE_APPLICATION_CREDENTIALS environment variable. But I see how that would be more problematic with docker local run.
