### ISSUE TITLE
Feature request: Under a config flag, decouple STOW-RS request from DIMSE C-STORE-RQ handling

### ISSUE THREAD

**Issue by jasonklotzer** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#120]
Goal: Increase the amount of images/second that can be handled by a single association on a single instance of the adapter.

In load testing of an environment where the adapter is running on-prem in a VM, it was found that a single DICOM association is not able to process more than 2-3 images/second.

The underlying assumption is that this is due to the synchronous nature in which the adapter handles a single store request per association:
Request sequence:
(PACS) -> C-STORE-RQ -> (Adapter) -> STOW-RS -> (Healthcare API)
Response sequence:
(PACS) <- C-STORE-RES <- (Adapter) <- HTTP Code <- (Healthcare API)

This is further supported by the fact that the P50 of the HCAPI endpoint is in the 100ms range, yielding an absolute max throughput per association of 10 images/second, ignoring all other portions of the insertion pipeline.

The suggested approach to improve the amount of image/second/association is to decouple the flow of data between (PACS) and (Adapter) from that of the (Adapter) and (Healthcare API), via thread pool or some other primitive with asynchronous support.

**Comment by jasonklotzer** [comment]
@danielbeaudreau

**Comment by luxunxiansheng** [comment]
Hi, there, 
       Is there any timeline on this enhancement to be done ?    Many thanks

L.B.

**Comment by jasonklotzer** [comment]
Apologies for the delay. This feature is under code review and should be available shortly.
