### ISSUE TITLE
Add versioning to containers 

### ISSUE THREAD

**Issue by danielbeaudreau** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#13]
Please see comment below for a description of this task.

**Comment by danielbeaudreau** [comment]
The plan is to have a cloud build trigger which runs after each commit to master:

- Runs unit tests to ensure they pass
- Automatically builds the docker containers
- Runs integration tests against the docker containers
- If tests pass, publish a new image to a gcr.io location tagged with the commit ID of the commit 
  which was built. Note that the gcr.io location will be new (different from existing one) so we don’t 
  risk breaking any users. We’ll use the following new URLS:
  gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-import:{version id}
  gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-export:{version id}
- Applies a version number to the container of the format vX.Y.Z where:
  We increment X manually on breaking changes
  We increment Y manually on new feature additions
  Cloud build script auto-increments Z

**Comment by danielbeaudreau** [comment]
Hi Egor, this is ready to be worked on now.

We will need to make some configuration changes in the oss-test project for this to work. I can make these changes once we have the basic cloud build file in a PR.

**Comment by danielbeaudreau** [comment]
This is working now. 
https://pantheon.corp.google.com/gcr/images/cloud-healthcare-containers/GLOBAL/healthcare-api-dicom-dicomweb-adapter-import?gcrImageListsize=30

**Comment by pavertomato** [comment]
> This is working now.
> https://pantheon.corp.google.com/gcr/images/cloud-healthcare-containers/GLOBAL/healthcare-api-dicom-dicomweb-adapter-import?gcrImageListsize=30

this link is available only for googlers:(

**Comment by danielbeaudreau** [comment]
Woops, thanks for catching that.
This is the link:
gcr.io/cloud-healthcare-containers/healthcare-api-dicom-dicomweb-adapter-import

**Comment by dzelemba** [comment]
Two small things left here:
  1) Cleanup README to use new container
  2) Add WIKI page describing release process.

**Comment by pavertomato** [comment]
https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/wiki/Release-process
is updated
