### ISSUE TITLE
Change integration test to use healthcare-dicom-dicomweb-adapter-test dataset

### ISSUE THREAD

**Issue by danielbeaudreau** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#16]
We gave the service account permissions to create dicom stores, but not datasets. We want to re-use datasets between integration test runs. Please update the test to use this dataset (note: location is us-central1, for consistency with the dicom fuse repo)

**Comment by red1408** [comment]
Ok, changed defaults to these values.
