### ISSUE TITLE
Deprecate stow path, introduce a new parameter for the dicom web address

### ISSUE THREAD

**Issue by danielbeaudreau** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#19]
From https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/pull/18:

Add a new flag for dicom web address which is mandatory to use CFIND and CMOVE, which is the dicomweb path up to /dicomWeb. We can use only this for CFIND and CMOVE. For CSTORE since we have legacy clients we should support both ways of specifying the path for a while. Note that CFIND and CMOVE won't work with the current way of specifying the path in the readme file above, because the complete path is not part of the dicomweb_addr param.

Mark the old stow path flag as deprecated in a comment, and explain how to migrate to the new way of specifying the flag in the readme, as well as updating the example in the readme.

Eventually we can remove the stow path.

**Comment by red1408** [comment]
What do you think would be a good name for new full dicomweb address parameter? Something like "--dicomweb_addr_full" just looks superfluous.

**Comment by danielbeaudreau** [comment]
Maybe we can just use --dicomweb_address and update our readme to use the new param. The old param can just exist in the flags file for now, and we can handle it on the server side for now, but all new users will specify the --dicomweb_address.

**Comment by danielbeaudreau** [comment]
This is mainly done, however we'd like to also deprecate the peer addr/stowpath in the export adapter.
