### ISSUE TITLE
Provide Sample Data Protect Toolkit Configs

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#21]
Data protect toolkit: https://github.com/GoogleCloudPlatform/healthcare/tree/master/deploy,

Provide a sample config file that shows how to deploy the adapters as part of the DPT config file.

**Comment by pavertomato** [comment]
should adapter be part of dpt repo as git submodule and builded by bazel?

**Comment by dzelemba** [comment]
No we should just provide some sample configs in this repo that work with the DPT.

**Comment by pavertomato** [comment]
not sure if i understand this correctly 
do we need to create something like https://github.com/GoogleCloudPlatform/healthcare/blob/master/deploy/samples/project_with_local_audit_logs.yaml with placeholders for AETs which will create sample project with dicom adapters?

**Comment by dzelemba** [comment]
Yup exactly! The idea is that if someone is already using the DPT config files to control their project configuration they can easily add a snippet to that config file to include the adaptors.

**Comment by dzelemba** [comment]
Can we also add section to the README that points to this file? Otherwise this isn't very discoverable.
