### ISSUE TITLE
Support DeID'ing files as they go through the adaptor

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#22]
Using https://github.com/GoogleCloudPlatform/healthcare-deid/tree/master/offline_tools/redactor

**Comment by pavertomato** [comment]
do we have any kind of maven repo where jar of this tool is available? or it have to be compiled with adapter?

**Comment by dzelemba** [comment]
I think the team was working on making it available through maven, let me check.

**Comment by danielbeaudreau** [comment]
Thanks Egor, can you please create a PR to update the readme as well?

**Comment by red1408** [comment]
Sure, will do it tomorrow.
