### ISSUE TITLE
Build failure - could not resolve dependencies

### ISSUE THREAD

**Issue by kokokenada** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#39]
Following the instructions in the README to Build From source (`gradle build` in import) results in:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/kenono/apps/healthcare-dicom-dicomweb-adapter/export/build.gradle' line: 93

* What went wrong:
A problem occurred evaluating project ':export'.
> Could not resolve all dependencies for configuration ':export:runtime'.
   > Could not resolve org.dcm4che:dcm4che-dict:3.3.8.
     Required by:
         project :export > org.dcm4che:dcm4che-core:3.3.8
      > Could not resolve org.dcm4che:dcm4che-dict:3.3.8.
         > Could not get resource 'https://jitpack.io/org/dcm4che/dcm4che-dict/3.3.8/dcm4che-dict-3.3.8.jar'.
            > Could not HEAD 'https://jitpack.io/org/dcm4che/dcm4che-dict/3.3.8/dcm4che-dict-3.3.8.jar'. Received status code 522 from server: Origin Connection Time-out
   > Could not resolve com.github.DanielN:multipart-handler:1.0-beta1.
     Required by:
         project :export > project :dicom_util
      > Skipped due to earlier error
```

**Comment by danielbeaudreau** [comment]
https://jitpack.io/org/dcm4che/dcm4che-dict/3.3.8/dcm4che-dict-3.3.8.jar seems to give me a timeout error as well.

Maybe we will need to change the repository for these packages to a different source, if possible.

**Comment by EduardoSantanaSeverino** [comment]
@danielbeaudreau, is possible that you point out any other repository sources that we use?

**Comment by pavertomato** [comment]
dcm4che jar should be downloaded from http://www.dcm4che.org/maven2/ and it's present in configuration
`maven { url 'http://www.dcm4che.org/maven2/' }`
and for this moment cloud build and my local gradle works fine for export and import adapter
i see few options here
- dcm4che.org was unavailable for some period of time, could you please check again?
- your custom gradle config forbids   to use dcm4che.org as resuorse of jars, could you please check it?
- your version of gradle does not support java 11, could you please try to use gradle:5.6-jdk11 ?

**Comment by danielbeaudreau** [comment]
I tried building locally after clearing cache in the import directory, I got the following error:

FAILURE: Build failed with an exception.

* Where:
Build file '/usr/local/google/home/dbeaudreau/adapter-test/healthcare-dicom-dicomweb-adapter/export/build.gradle' line: 93

* What went wrong:
A problem occurred evaluating project ':export'.
> Could not resolve all dependencies for configuration ':export:runtime'.
   > Could not resolve com.github.DanielN:multipart-handler:1.0-beta1.
     Required by:
         project :export > project :dicom_util
      > Skipped due to earlier error

It looks like the com.github.DanielN:multipart-handler:1.0-beta1 package can't be resolved.

**Comment by pavertomato** [comment]
> It looks like the com.github.DanielN:multipart-handler:1.0-beta1 package can't be resolved.

have you removed line with `maven { url 'https://jitpack.io' }`?

because https://jitpack.io/com/github/DanielN/multipart-handler/1.0-beta1/multipart-handler-1.0-beta1.jar
and https://jitpack.io/com/github/DanielN/multipart-handler/1.0-beta1/multipart-handler-1.0-beta1.pom is available

**Comment by danielbeaudreau** [comment]
Hmm, no I haven't, it was with a clean clone of the repo. It's working for you after clearing your cache? https://stackoverflow.com/a/30450020
I was using gradle5.4.1 if that makes a difference.

**Comment by pavertomato** [comment]
> Hmm, no I haven't, it was with a clean clone of the repo. It's working for you after clearing your cache? https://stackoverflow.com/a/30450020
> I was using gradle5.4.1 if that makes a difference.

yep, i've tried to delete cache and maven local repo, build still successful 
![image](https://user-images.githubusercontent.com/878990/65282287-c29d2c80-db5e-11e9-9d3a-8426bd4d96a3.png)
just downloaded(gmt+3)

>gradle5.4.1 
i think it should be fine
may be access to https://jitpack.io is forbidden from your network?

**Comment by danielbeaudreau** [comment]
I don't think so, I'm able to visit the jitpack.io URLs.
I wonder if our presubmit builds are broken by this.

**Comment by pavertomato** [comment]
> I wonder if our presubmit builds are broken by this.

it would build weird because cloud build(at least on our projects) still builds both adapters 
i think root cause is local configuration of gradle because it have wide set of configurations oustide of projects and sometime it may be confusing

**Comment by jyliu3** [comment]
I added the com.github.DanielN:multipart-handler:1.0-beta1 jar file manually to the project ,and use java 11, it is ok now.

**Comment by red1408** [comment]
Tried about 10 cloud build attempts over period of 2 days, all successful. It seems core issue was transient repository unavailability.
