### ISSUE TITLE
Where can I get documentation

### ISSUE THREAD

**Issue by EduardoSantanaSeverino** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#40]
Dear fellows, 

I have been trying to get documentation about this code. and I can not find any. 

I see commits mostly from @red1408 and @pavertomato . . . 

Is it possible to get any documentation about this code?

1.    Installation Steps (without Kubernetes.)
2.    How to run for the first time (NO the test, but hosted on a local server)
3.    Basic Usage Examples.
4.    Architecture Code Details.

Warm Regards,

**Comment by red1408** [comment]
1)There is no installation per se. You just run Import or Export adapter with correct command line parameters/environment.
2-3)There are few examples how do it in Readme https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter and Wiki https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/wiki (there is a docker case, but now that I look at it may also be the best demonstration of full command).
4) For more detailed overview, DICOM Conformance Statement may be of help, when it's done. Currently it is in the works.

**Comment by dzelemba** [comment]
I've updated the main README.md to make it easier to find the local deployment instructions which should hopefully answer your questions. If you're still have issues please feel free to re-open!
