### ISSUE TITLE
Support QIDO-RS pagination when handling C-FIND requests

### ISSUE THREAD

**Issue by red1408** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#42]
The default number of results is 100 for studies/series and 1,000 for instances.

**Comment by red1408** [comment]
Ok, added to C-FIND section of conformance statement.

**Comment by danielbeaudreau** [comment]
We want to convey some warning to the user when there are 50,000 C-FIND results indicating that there may be more results. But, C-FIND doesn't support the "warning" status. Egor can you please investigate how other C-FIND implementations handle this scenario to determine what the standard is? Thanks.

**Comment by red1408** [comment]
Right, there is no standard "warning" status for C-FIND.
As for what others do: I've looked through first several pages worth of DICOM Conformance statements for various stuff on google. C-FIND result limit was mentioned a few times, but only in SCUs (not a problem at SCU side, just cancel on hitting limit). So this provided no solution as well.

As for more abstract ideas, I suppose I could append a fake result with potentially displayable fields stuffed with "Hit result limit" in some way, hoping that user will notice the unusual result. But this is quite dubious - a user that attentive would already notice that 5000/50000 is too round number anyway. And depending on how client sorts results presented to user, the fake result might be hidden somewhere in the middle of result list.

**Comment by red1408** [comment]
@danielbeaudreau 
As I've noted above, a good way to do this doesn't seem to exist.

**Comment by danielbeaudreau** [comment]
Since we have this documented in our conformance statement, and there's no way to include a warning in a c-find response, I think we can close this for now.
