### ISSUE TITLE
Support routing to multiple DICOM stores

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#47]

**Comment by mukhlin** [comment]
Hi @dzelemba 

We have the following questions:

1. Is this issue related to export or import or both (and which services)?
1. How do you want to configure list of stores?
1. What is the criteria to choose particular store?
1. Are you expect change in Adapter or it can be implemented as separate application (for example, NGINX based proxy)?

**Comment by mukhlin** [comment]
Hi @danielbeaudreau,

Can you please have a look at my comment above as well?

**Comment by danielbeaudreau** [comment]
Hi, I'll get back to you on this soon.

**Comment by dzelemba** [comment]
More detailed requirements are available in https://docs.google.com/document/d/1pWzEUkORVm5kpNWoa9xQsGLOPleZ3MfXA91GHPzy1R8/edit
