### ISSUE TITLE
Redactor lib introduced dependency version conflict

### ISSUE THREAD

**Issue by red1408** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#48]
Not hit by integration test because crashes happen when initializing CHC_BASIC profile in redactor or starting monitoring.
Updated some dependencies in adapter to solve the problem.

**Comment by danielbeaudreau** [comment]
Why did it only happen for the chc_basic profile and not the redact_remove_list?
I think we should consider adding an integration test for monitoring, how much effort do you think this would be?

**Comment by red1408** [comment]
> Why did it only happen for the chc_basic profile and not the redact_remove_list?

https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/pull/49#discussion_r345030110

> I think we should consider adding an integration test for monitoring, how much effort do you think this would be?

Just adding monitoring initialization with global scope is easy (which would have been enough to notice this particular problem).  I'm not sure how I could actually validate monitoring data though, a relevant gcloud alpha command doesn't seem to exist. Setting up container-level monitored object would also add difficulty, if it's needed.

**Comment by danielbeaudreau** [comment]
Let's add the basic monitoring initialization with global scope.

**Comment by red1408** [comment]
Ok, added basic monitoring initialization to pull request.
