### ISSUE TITLE
Hide failed to load aet direction exception

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#59]
Instead of throwing an exception, can we print an error saying that C-MOVE hasn't been configured? It makes it look the adaptor failed to startup when it runs just fine for C-STORE/C-FIND.

**Comment by red1408** [comment]
Looks like recent refactoring within https://github.com/GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter/pull/57 already changed this behavior.
Exception is only thrown if we try and fail to parse one of possible aet dictionary sources (rather than all of them being unused/empty).

**Comment by dzelemba** [comment]
Yup confirmed this is fixed in release 0.1.14.
