### ISSUE TITLE
Create GitHub Release Entry for Automated Releases

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#60]
This will make releases more discoverable.

**Comment by danielbeaudreau** [comment]
I'm getting a not found response from Github after merging the recent PR. Have you seen this one before?

Step #29 - "publish-image": #=#=#                                                                         

######################################################################## 100.0%
######################################################################## 100.0%
Step #29 - "publish-image": {
Step #29 - "publish-image":   "message": "Not Found",
Step #29 - "publish-image":   "documentation_url": "https://developer.github.com/v3/repos/releases/#create-a-release"
Step #29 - "publish-image": }
Finished Step #29 - "publish-image"
ERROR
ERROR: build step 29 "google/cloud-sdk:272.0.0" failed: step exited with non-zero status: 1

**Comment by pavertomato** [comment]
> I'm getting a not found response from Github after merging the recent PR. Have you seen this one before?
> 
> Step #29 - "publish-image": #=#=#
> 
> ######################################################################## 100.0%
> ######################################################################## 100.0%
> Step #29 - "publish-image": {
> Step #29 - "publish-image": "message": "Not Found",
> Step #29 - "publish-image": "documentation_url": "https://developer.github.com/v3/repos/releases/#create-a-release"
> Step #29 - "publish-image": }
> Finished Step #29 - "publish-image"
> ERROR
> ERROR: build step 29 "google/cloud-sdk:272.0.0" failed: step exited with non-zero status: 1

yep, looks like github api is not enabled for repo or robot user don't have permissions
https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/issues/6#issuecomment-510118455
or i may add debug line to print url to make sure what $ REPO_NAME is not changed, but since recent releases of other projects are fine, it seems not

**Comment by danielbeaudreau** [comment]
Fixed now.
