### ISSUE TITLE
Add basic validation of DICOMweb addresses

### ISSUE THREAD

**Issue by dzelemba** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#62]
E.g. if someone appends an extra "/studies"  to --dicomweb_address they will get hard to debug errors because we'll attach an extra "/studies" which the server will interpret as the StudyUID being uploaded into.

**Comment by danielbeaudreau** [comment]
Let's also handle the case where the --dicomweb_address paramter has a "/" at the end. Currently we append "/studies" regardless of the parameter value, which will cause a 404

**Comment by jasonklotzer** [comment]
+2 :)

**Comment by red1408** [comment]
I think such validation should be conditional - adapter can be used with other dicomweb services,  which don't follow same path convention.

Maybe add "--non-google-dicomweb" parameter to be able to skip google-specific validation.

**Comment by jasonklotzer** [comment]
I guess my main curiosity is: Why append '/studies' within the code in the first place if the expectation is for a standard DICOMweb stow-rs path as input? That would presume the input should always contain `/studies` or `/studies/{studyUid}`? Having path magic done within the code is hard for a consumer to be aware of.

**Comment by red1408** [comment]
C-store always uploads to /studies, but other service (C-find, C-Move, Storage commitment ) use /series and /instances as well.
Overall dicomweb endpoint is expected to support not only stow-rs, but qido-rs and wado-rs as well.

**Comment by jasonklotzer** [comment]
Maybe provide configuration paths for each as input? It may be less practical for the user, but that way the code isn't guessing.

**Comment by danielbeaudreau** [comment]
I think we can assume that the path should probably never end in /studies or a trailing slash, so we could at least throw an error in that case for usability

**Comment by red1408** [comment]
- For google healthcare path I could simply check vs regex "https:\\/\\/healthcare.googleapis.com\\/.*?\\/projects\\/.*?\\/locations\\/.*?\\/datasets\\/.*?\\/dicomStores\\/.*?\\/dicomWeb"
- Trailing slash is simple enough to ignore when present, so I could just discard it before check
- For non-google path (not starting with "https://healthcare.googleapis.com") I'd check that it doesn't end with /studies (though this means that typo in begging of google path would cause it to be interpreted as non-google).

Is this alright?

**Comment by danielbeaudreau** [comment]
Yeah that seems reasonable to me. Thanks
