### ISSUE TITLE
Adding DateShiftConfig | CharacterMaskConfig | CryptoHashConfig functionality as part of current de-identification process

### ISSUE THREAD

**Issue by manishadubaria** [GoogleCloudPlatform/healthcare-dicom-dicomweb-adapter#92]
Can leverage the functionality of DateShiftConfig, CharacterMaskConfig, and CryptoHashConfig of healthcare API in DicomAdapter Code piece.
**DateShiftConfig**: By using this config Cloud Healthcare API can transform dates by shifting them within a preset range. Could be very useful when you want date transformations to remain consistent across de-identification.
**CharacterMaskConfig**: BY using this config Cloud Healthcare API replaces strings that correspond to the given infoTypes with a specified fixed character. For eg: Rather than redacting a patient's name, you can replace the name with a series of asterisks(*).
**CryptoHashConfig**: By using this config Cloud Healthcare API can transform data by replacing values with cryptographic hashes. Could be useful when instead of redaction the values need to be hashed.

**Comment by dzelemba** [comment]
Hello! Thanks for filling the FR.

The redaction capabilities in the dicom adapter are powered by https://github.com/GoogleCloudPlatform/healthcare-deid/tree/master/offline_tools/redactor, not by the Healthcare API. If you'd like these capabilities to be available offline, please file a feature request in that repo. Or, if you'd like to use these feature as part of the Healthcare API, you can follow https://cloud.google.com/healthcare/docs/how-tos/dicom-deidentify.

I'll close this issue, but feel free to comment if you have any other questions!
